version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}