---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: API_KEY
  weatherapi: weatherapiapikey

title: DrTableBasse 
background:
  image: https://imgur.com/4shKIzi.gif
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50
theme: dark
color: gray
language: fr
hideVersion: true
hideErrors: true
headerStyle: boxedWidgets



