---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

- weatherapi:
    label: Aix-en-Provence #optional
    latitude: 43.53
    longitude: 5.45
    units: metric # or imperial
    provider: weatherapi
    apiKey: API_KEY # required only if not using provider, this reveals api key in requests
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
