#cloud-config

# On met à jour le système
package_update: true
package_upgrade: true

# On créé l'utilisateur avec droits sudo en précisant sa clé SSH publique
users:
  - default
  - name: user
    groups: [ wheel, sudo ]
    shell: /bin/bash
    homedir: /home/user
    sudo: ['ALL=(ALL) NOPASSWD:ALL']


# On installe les applications nécessaires
packages:
  - curl
  - fio
  - git
  - htop
  - ioping
  - neofetch
  - nload
  - p7zip-full
  - docker.io
  - zip

runcmd:
  # On se place dans le dossier de l'utilisateur
  - cd /home/user

  # On ajoute un alias pour mettre à jour facilement le système
  - echo "alias fup='sudo apt update && sudo apt full-upgrade -y && sudo apt autoremove -y'" >> .bashrc

  # On coupe l'accès au compte root pour la connexion SSH
  - sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin no/g' /etc/ssh/sshd_config
  - systemctl restart sshd.service


  # On ajoute l'utilisateur davlgd au groupe docker
  - usermod -aG docker user

final_message: "Le système est configuré. Délai nécessaire : $UPTIME secondes"
