#cloud-config
autoinstall:
  version: 1

  locale: fr_FR.UTF-8
  keyboard:
    layout: fr
  timezone: Europe/Paris

  network:
    version: 2
    ethernets:
      enp0s3:
        dhcp4: true

  identity:
    username: egidio #nom du user que l'on souhaite
    hostname: linuxconfig
    password: '$6$WZKXRHiq6/DPc03E$Nd3jHz7KsgMCT/mgXof4Oeh9.UEQgqQpLoJqrUVFAQeLLnFza7QHHKRQ8Fc/K2sGn4QkrM57Sd1QUuy3HjQ5t1' #hash du mdp 'toto' --> openssl passwd -6 toto

  ssh:
    install-server: true
    allow-pw: true
    authorized-keys: []

  packages:
    - git
    - python3-pip

  snaps:
    - name: pycharm-community
      channel: stable 
      classic: true

  storage:
    config:
      - id: disk-sda
        type: disk
        ptable: gpt
        path: /dev/sda
        wipe: superblock-recursive

      # EFI System Partition
      - id: efipart
        type: partition
        device: disk-sda
        size: 512M
        flag: boot
        grub_device: true

      - id: bootpart
        type: partition
        device: disk-sda
        size: 1G

      - id: pvpart
        type: partition
        device: disk-sda
        size: -1

      - id: vg0
        type: lvm_volgroup
        name: vg0
        devices:
          - pvpart

      - id: root_lv
        type: lvm_partition
        name: root_lv
        volgroup: vg0
        size: 10G
 
      - id: home_lv
        type: lvm_partition
        name: home_lv
        volgroup: vg0
        size: 5G

      # Formats
      - id: efipart_fs
        type: format
        volume: efipart
        fstype: fat32

      - id: bootpart_fs
        type: format
        volume: bootpart
        fstype: ext4

      - id: root_lv_fs
        type: format
        volume: root_lv
        fstype: ext4

      - id: home_lv_fs
        type: format
        volume: home_lv
        fstype: ext4

      # Mounts
      - id: efipart-mount
        type: mount
        device: efipart_fs
        path: /boot/efi

      - id: bootpart-mount
        type: mount
        device: bootpart_fs
        path: /boot

      - id: root_lv_mount
        type: mount
        device: root_lv_fs
        path: /

      - id: home_lv_mount
        type: mount
        device: home_lv_fs
        path: /home

  shutdown: reboot
